project = 'pandoc-zotxt.lua'
description = 'Pandoc filter that looks up sources of citations in Zotero.' 
full_description = [[pandoc-zotxt.lua looks up sources of citations in Zotero
and adds them either to a document's references metadata field or to a
bibliography file, where Pandoc can pick them up.

It requires zotxt. 

See <https://github.com/odkr/pandoc-zotxt.lua> for details.]]
file = 'pandoc-zotxt.lua'
format = 'markdown'
readme = 'README.md'
dir = 'docs'
