#!/bin/sh
# release-publish - Publish a release on GitHub.
# See -h for details.
# Copyright 2021 Odin Kroeger
# Released under the MIT license.
# shellcheck disable=2015

set -Ceu


# CONSTANTS
# =========

# The top-level directory of the git repository.
REPO="$(git rev-parse --show-toplevel)" && [ "$REPO" ] || {
	SCPT_NAME="$(basename "$0")" && [ "$SCPT_NAME" ] || SCPT_NAME="$0"
	printf '%s: failed to find repository.\n' "$SCPT_NAME" >&2
	exit 69
}
readonly REPO


# LIBRARY
# =======

LIBRARY="$REPO/scripts/library.sh"
# shellcheck source=library.sh
. "$LIBRARY" || exit


# WORKING DIRECTORY
# =================

cd -P "$REPO" || exit 69


# DEFAULTS
# ========

# Where to look for the manifest file.
manifest=Manifest


# ARGUMENTS
# =========

filter=
OPTIND=1 OPTARG='' opt=
while getopts m:f:h opt
do
	case $opt in
		(f)	filter="$OPTARG" ;;
		(m)	manifest="$OPTARG" ;;
		(h)	exec cat <<-EOF
			$SCPT_NAME - publish a release on GitHub

			Synopsis:
			    $SCPT_NAME [-d DIR] [-f FILTER] [-m manifest]
			    $SCPT_NAME -h

			Options:
			    -f FILTER    The Lua filter.
			    -m MANIDEST  The manifest file.
			                 (Defaults to $manifest.)
			    -h           Show this help screen.
			EOF
			;;
		(*)	exit 70
	esac
done
shift $((OPTIND - 1))
[ $# -gt 0 ] && panic -s 64 'too many operands.'

for file in "$filter" "$manifest"
do
	[ -z "$file" ] || 
	[ -f "$file" ] || 
	panic -s 66 '%s: no such file.' "$file"
done
unset file

[ "${filter-}" ] || filter="$(guess_filter)" && [ "$filter" ] || exit


# PRELUDE
# =======

#temp_dir_make -d . -p rm
temp_dir_make -p rm
CLEANUP="git checkout develop; ${CLEANUP-}"


# MAIN
# ====

warn 'verifying version number ...'

release="$(sed -n 's/-- *@release *//p;' "$filter")" && [ "$release" ] ||
	panic '%s: failed to parse @release.' "$filter"

vers="$(sed -n "s/^ *VERSION *= *['\"]\([^'\"]*\)['\"].*/\1/p;" "$filter")" &&
	[ "$vers" ] || panic '%s: failed to parse VERSION.' "$filter"

[ "$release" = "$vers" ] ||
	panic -s 65 '%s: @release %s does not match VERSION v%s.' \
	       "$filter" "$release" "$vers"

for tag in $(git tag --list 'v*' --sort version:refname)
do
	[ "$tag" = "v$vers" ] &&
		panic 'v%s has been released already.' "$vers"
done
last="$tag"

[ "$last" ] || panic 'failed to determine latest release.'

warn 'verifying branch ...'

release_branch="release-$vers"
[ "$(git branch --show-current)" = "$release_branch" ] ||
 	panic 'not on "%s" branch.' "$release_branch"

while read -r fname || [ "$fname" ]
do
	case $fname in
		('#'*|'') continue ;;
		(*[Rr][Ee][Aa][Dd][Mm][Ee]*)
			grep --fixed-strings --quiet "$vers" "$fname" ||
			panic -s 65 '%s: does not reference v%s.' \
			      "$fname" "$vers"
	esac
done <"$manifest"

warn -e "$SMSO" 'updating documentation ...'

make docs
git add "$filter" man docs
git commit --quiet --message='docs: updated.' || :

warn -e "$SMSO" 'testing release ...'

test/scripts/test-pandoc-vers

warn -e "$SMSO" 'pushing changes in %s ...' "$BOLD$release_branch$SGR0$SMSO"

git push origin "$release_branch"

for branch in develop main
do
	warn -e "$SMSO" 'merging %s to %s ...' \
	     "$BOLD$release_branch$SGR0$SMSO" "$BOLD$branch$SGR0$SMSO"
	git checkout "$branch"
	git merge "$release_branch"
	
	if [ "$branch" != main ]
	then
		warn -e "$SMSO" 'pushing changes in %s ...' \
		        "$BOLD$branch$SGR0$SMSO"
		git push origin "$branch"
	fi
done

warn -e "$SMSO" 'collecting log ...'

log="$TEMP_DIR/log"
git log "^$last" HEAD >"$log"

warn -e "$SMSO" 'adding tag %s ...' "${BOLD}v${vers}${SGR0}${SMSO}"

git tag --file="$log" --edit "v$vers"

warn -e "$GREEN" done.
