--- pre-v2_11.lua - A fake Pandoc filter that checks Pandoc's version.
--
-- SYNOPSIS
-- --------
--
-- **pandoc** **-L** *pre-v2_11.lua* /dev/null
--
-- DESCRIPTION
-- -----------
--
-- Used in the test suite to tailor tests to different versions of Pandoc.
--
-- EXIT STATUS
-- -----------
--
--  0    If your copy of Pandoc is of version 2.11 or higher.
--  1    Otherwise.
--
-- AUTHOR
-- ------
--
-- Odin Kroeger
--
-- @script pre-v2_11.lua
-- @author Odin Kroeger
-- luacheck: ignore
if pandoc.types and PANDOC_VERSION >= {2, 11} then os.exit(1) end
